### ISSUE TITLE
nvcc fatal: Unsupported gpu architecture 'compute_86' ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by cql18381505437** [Ruyi-Zha/naf_cbct#15]
I configured the environment to run on RTX3090 with this "nvcc fatal: Unsupported gpu architecture 'compute_86' ninja: build stopped: subcommand failed. "I want to ask how to solve this?

**Comment by Ruyi-Zha** [comment]
Hi, this issue should be related to Cuda rather than our code. You might need to change the Cuda version in your system. You may find some solutions [here](https://github.com/NVIDIAGameWorks/kaolin/issues/351) and [here](https://stackoverflow.com/questions/69865825/nvcc-fatal-unsupported-gpu-architecture-compute-86).
