### ISSUE TITLE
IntraTomo3D baseline

### ISSUE THREAD

**Issue by wss182** [Ruyi-Zha/naf_cbct#16]
Thank you for your excellence in this project! 
Could you please tell me how to obtain the baseline results for IntraTomo? Is it through python code or other ways?

**Comment by Ruyi-Zha** [comment]
Thanks for your interest. Since the intraTomo code is not publicly available, we implement it in our own way. Specifically, we think of intraTomo as an X-ray version of NeRF. we replace the hash encoder in our method with a frequency encoder and use a bigger 6-layer 256-wide MLP, as shown in the intraTomo paper. You can do this by simply modifying the configuration file. Please note that the original intraTomo paper lacks many implementation details and is not originally for 3D CT reconstruction. We use intraTomo primarily as an example of ordinary NeRF for comparison.

**Comment by wss182** [comment]
你好，已收到邮件！

**Comment by wss182** [comment]
你好，已收到邮件！
