### ISSUE TITLE
Data acquisition

### ISSUE THREAD

**Issue by seongje-oh** [Ruyi-Zha/naf_cbct#17]
Hello, thank you for sharing your valuable code. Before applying your code, I would like to use the information written in chest_50.pickle to obtain projection data from img.mat data through TIGRE technology, but it comes out different from the shared data. Can you tell me how you acquired the traindata for this part?

**Comment by Ruyi-Zha** [comment]
Hi, we use `dataGenerator/generateData.py` to generate the pickle file. Do you mean you use the [raw data](https://drive.google.com/drive/folders/1qiPWmhseEVC3vZ4SmYUmopsaC-yEKKXZ?usp=drive_link) but cannot generate the same output as `chest_50.pickle`? Since there are some random operations, it is acceptable if your results are slightly different from ours. If they are quite different, could you please share more details so that I can see what's going on? Thanks.
